from __future__ import annotations

import base64
import json
import os
import time
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

WEB_BASE_URL = os.environ.get("QA_WEB_BASE_URL", "http://127.0.0.1:5173").rstrip("/")
TARGETS = ((1366, 768), (1280, 720), (1024, 768), (390, 844))
TOLERANCE_PX = 2
ARTIFACT_DIR = Path(".qa-artifacts/analytics-r3")
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

options = webdriver.ChromeOptions()
options.add_argument("--headless=new")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-gpu")
options.add_argument("--force-device-scale-factor=1")
options.set_capability("goog:loggingPrefs", {"browser": "ALL"})

browser_bin = os.environ.get("BROWSER_BIN")
if browser_bin:
    options.binary_location = browser_bin

driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 20)
results: list[dict[str, object]] = []


def set_viewport(width: int, height: int) -> None:
    driver.execute_cdp_cmd(
        "Emulation.setDeviceMetricsOverride",
        {"width": width, "height": height, "deviceScaleFactor": 1, "mobile": False},
    )
    time.sleep(0.25)
    driver.execute_script("window.scrollTo(0, 0)")


def capture(name: str) -> tuple[str, str]:
    viewport_path = ARTIFACT_DIR / f"{name}.png"
    driver.save_screenshot(str(viewport_path))
    full_path = ARTIFACT_DIR / f"{name}-full.png"
    full_capture = driver.execute_cdp_cmd(
        "Page.captureScreenshot",
        {"format": "png", "captureBeyondViewport": True, "fromSurface": True},
    )
    full_path.write_bytes(base64.b64decode(full_capture["data"]))
    return str(viewport_path), str(full_path)


def track_count(value: str) -> int:
    return len([part for part in value.split(" ") if part.strip()])


try:
    set_viewport(1366, 768)
    driver.get(f"{WEB_BASE_URL}/operator/login")
    wait.until(lambda d: d.execute_script("return document.readyState") == "complete")
    wait.until(EC.visibility_of_element_located((By.ID, "operator-login"))).send_keys(
        "analytics.supervisor@eliasworks.invalid"
    )
    driver.find_element(By.ID, "operator-password").send_keys("visual-qa-password")
    submit = wait.until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, "form.operator-form button[type='submit']"))
    )
    driver.execute_script("arguments[0].scrollIntoView({block:'center'});", submit)
    submit.click()
    wait.until(lambda d: "/operator/" in d.current_url and "/login" not in d.current_url)

    analytics_link = wait.until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, "a.operator-sidebar-item[href='/operator/analytics']"))
    )
    driver.execute_script("arguments[0].scrollIntoView({block:'center'});", analytics_link)
    analytics_link.click()
    wait.until(lambda d: d.current_url.endswith("/operator/analytics"))
    wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".r3-increment-07-analytics")))
    wait.until(EC.visibility_of_element_located((By.XPATH, "//h1[contains(., 'Métricas operacionales')]")))
    wait.until(lambda d: "Respuesta R3 autoritativa" in d.find_element(By.CSS_SELECTOR, ".claims-analytics-provenance").text)
    wait.until(lambda d: "128" in d.find_element(By.CSS_SELECTOR, ".r3-canonical-kpis").text)
    wait.until(lambda d: "Evaluación" in d.find_element(By.CSS_SELECTOR, ".claims-analytics-grid").text)

    # Ignore transient console noise generated by the post-login landing route.
    driver.get_log("browser")

    for width, height in TARGETS:
        set_viewport(width, height)
        time.sleep(0.15)

        metrics = driver.execute_script(
            """
            const root = document.documentElement;
            const body = document.body;
            const page = document.querySelector('.r3-increment-07-analytics');
            const heading = document.querySelector('.claims-analytics-heading');
            const title = document.querySelector('.claims-analytics-heading h1');
            const select = document.querySelector('.r3-window-control select');
            const refresh = document.querySelector('.claims-analytics-actions .ops-refresh-button');
            const provenance = document.querySelector('.claims-analytics-provenance');
            const kpis = document.querySelector('.r3-canonical-kpis');
            const firstKpi = document.querySelector('.r3-canonical-kpis .ops-kpi-card');
            const grid = document.querySelector('.claims-analytics-grid');
            const firstPanel = document.querySelector('.claims-analytics-panel');
            const firstBarRow = document.querySelector('.claims-analytics-bar-row');
            const kpiStyle = kpis ? getComputedStyle(kpis) : null;
            const gridStyle = grid ? getComputedStyle(grid) : null;
            return {
              innerWidth: window.innerWidth,
              innerHeight: window.innerHeight,
              scrollWidth: Math.max(root.scrollWidth, body.scrollWidth),
              scrollHeight: Math.max(root.scrollHeight, body.scrollHeight),
              pageWidth: page ? Math.round(page.getBoundingClientRect().width) : 0,
              headingHeight: heading ? Math.round(heading.getBoundingClientRect().height) : 0,
              titleFont: title ? parseFloat(getComputedStyle(title).fontSize) : 0,
              selectHeight: select ? Math.round(select.getBoundingClientRect().height) : 0,
              refreshHeight: refresh ? Math.round(refresh.getBoundingClientRect().height) : 0,
              provenanceHeight: provenance ? Math.round(provenance.getBoundingClientRect().height) : 0,
              kpiColumns: kpiStyle ? kpiStyle.gridTemplateColumns : '',
              kpiHeight: firstKpi ? Math.round(firstKpi.getBoundingClientRect().height) : 0,
              gridColumns: gridStyle ? gridStyle.gridTemplateColumns : '',
              panelWidth: firstPanel ? Math.round(firstPanel.getBoundingClientRect().width) : 0,
              barRowHeight: firstBarRow ? Math.round(firstBarRow.getBoundingClientRect().height) : 0,
            };
            """
        )
        overflow = metrics["scrollWidth"] - metrics["innerWidth"]
        shot, full = capture(f"analytics-r3-{width}x{height}")

        if overflow > TOLERANCE_PX:
            raise AssertionError(f"Analytics horizontal overflow at {width}x{height}: {overflow}px")

        kpi_columns = track_count(str(metrics["kpiColumns"]))
        grid_columns = track_count(str(metrics["gridColumns"]))

        if width >= 1200:
            if metrics["titleFont"] > 30:
                raise AssertionError(f"Analytics title is oversized: {metrics['titleFont']}px")
            if metrics["headingHeight"] > 105:
                raise AssertionError(f"Analytics heading wastes vertical space: {metrics['headingHeight']}px")
            if metrics["provenanceHeight"] > 62:
                raise AssertionError(f"Analytics provenance strip is too tall: {metrics['provenanceHeight']}px")
            if kpi_columns < 6:
                raise AssertionError(f"Desktop Analytics must preserve six KPI columns: {metrics['kpiColumns']}")
            if metrics["kpiHeight"] > 116:
                raise AssertionError(f"Analytics KPI cards lost approved density: {metrics['kpiHeight']}px")
            if grid_columns < 2:
                raise AssertionError(f"Desktop Analytics lost two-panel composition: {metrics['gridColumns']}")
            if metrics["barRowHeight"] > 46:
                raise AssertionError(f"Analytics distribution rows are too tall: {metrics['barRowHeight']}px")
        elif width <= 1100:
            if grid_columns != 1:
                raise AssertionError(f"Narrow Analytics must stack distribution panels: {metrics['gridColumns']}")
            if width >= 720 and kpi_columns < 3:
                raise AssertionError(f"Tablet Analytics should keep at least three KPI columns: {metrics['kpiColumns']}")

        if width <= 520:
            if metrics["titleFont"] > 23:
                raise AssertionError(f"Analytics mobile title is oversized: {metrics['titleFont']}px")
            if kpi_columns != 2:
                raise AssertionError(f"Analytics mobile must use two KPI columns: {metrics['kpiColumns']}")
            for name, value in (("window select", metrics["selectHeight"]), ("refresh", metrics["refreshHeight"])):
                if value < 44:
                    raise AssertionError(f"Analytics mobile {name} target is too short: {value}px")

        results.append(
            {
                "width": width,
                "height": height,
                **metrics,
                "horizontalOverflow": overflow,
                "screenshot": shot,
                "fullPageScreenshot": full,
            }
        )

    severe = [
        entry.get("message", "")
        for entry in driver.get_log("browser")
        if entry.get("level") == "SEVERE" and "favicon.ico" not in entry.get("message", "")
    ]
    if severe:
        raise AssertionError(f"Browser console contained severe errors: {severe[:10]}")
finally:
    try:
        driver.execute_cdp_cmd("Emulation.clearDeviceMetricsOverride", {})
    except Exception:
        pass
    driver.quit()

print(json.dumps({"event": "ANALYTICS_R3_VIEWPORT_PASS", "viewports": results}, ensure_ascii=False))
